version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"        # Location of requirements.txt
    schedule:
      interval: "weekly"  # Scan every week
    allow:
      - dependency-name: "yt-dlp"
      - dependency-name: "requests"
      - dependency-name: "PyQt5"
      - dependency-name: "qtawesome"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
